name: Nginx 8.3

on:
  workflow_dispatch:

jobs:
  push:
    name: "nginx-ptero:8.3"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: maki-sevice-shop
          password: ${{ secrets.CR_PAT }}
          logout: true
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/maki-service-shop/nginx-ptero:8.3
