name: Nginx 8.3

on:
  workflow_dispatch:

jobs:
  push:
    name: "nginx-ptero:8.3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/maki-service-shop/nginx-ptero:8.3
          no-cache: true  # Add the no-cache flag to clear cache
